

service: requests


provider:
  name: aws
  stage: dev
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"


functions:
  createRequestNewPTO:
    handler: request.create
    events:
      - http:
          path: request
          method: post
          cors: true

  listRequestNewPTO:
    handler: request.list
    events:
      - http:
          path: request
          method: get
          cors: true

  getRequestNewPTO:
    handler: request.get
    events:
      - http:
          path: request/{requestid}
          method: get
          cors: true
          request:
            parameters:
              paths:
                requestid: true
  getEmployeeRequestNewPTO:
    handler: request.getEmployeeRequests
    events:
      - http:
          path: request/employee/{employeeid}
          method: get
          cors: true
          request:
            parameters:
              paths:
                employeeid: true
  getApproverRequestNewPTO:
    handler: request.getApproverRequests
    events:
      - http:
          path: request/approver/{employeeid}
          method: get
          cors: true
          request:
            parameters:
              paths:
                employeeid: true
  updateRequestNewPTO:
    handler: request.update
    events:
      - http:
          path: request/{requestid}
          method: put
          cors: true
          request:
            parameters:
              paths:
                requestid: true
  deleteRequestNewPTO:
    handler: request.delete
    events:
      - http:
          path: request/{requestid}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                requestid: true

resources:  
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RequestNewPTO
        AttributeDefinitions:
          - AttributeName: requestid
            AttributeType: S
          - AttributeName: requestedBy
            AttributeType: S
          - AttributeName: approvedBy
            AttributeType: S
        KeySchema:
          - AttributeName: requestid
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: "EmployeeRequests"
            KeySchema:
              - AttributeName: requestedBy
                KeyType: HASH
              - AttributeName: requestid
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: "ApproverRequests"
            KeySchema:
              - AttributeName: approvedBy
                KeyType: HASH
              - AttributeName: requestid
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: arn:aws:dynamodb:*:*:table/RequestNewPTO
        Roles:
          - Ref: IamRoleLambdaExecution